apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: studentapp
data:
  schema.sql: |
    -- Create Students Table
    CREATE TABLE IF NOT EXISTS students (
        student_id INT AUTO_INCREMENT PRIMARY KEY,
        student_name VARCHAR(100) NOT NULL,
        student_addr VARCHAR(200) NOT NULL,
        student_age VARCHAR(10) NOT NULL,
        student_qual VARCHAR(100) NOT NULL,
        student_percent VARCHAR(10) NOT NULL,
        student_year_passed VARCHAR(10) NOT NULL
    );
