apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: studentapp
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-database: c3R1ZGVudGRi
  mysql-user: c3R1ZGVudHVzZXI=
  mysql-password: c3R1ZGVudHBhc3N3b3Jk
